//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix_Apps
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierShifts
    {
        public int ShiftID { get; set; }
        public int CashierID { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<int> TotalTransactions { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
