//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix_Apps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.Showtimes = new HashSet<Showtimes>();
        }
    
        public int MovieID { get; set; }
        public string Title { get; set; }
        public int GenreID { get; set; }
        public int Duration { get; set; }
        public string Director { get; set; }
        public string Producer { get; set; }
        public string Cast { get; set; }
        public string AgeRating { get; set; }
        public string Synopsis { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string PosterImage { get; set; }
    
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Showtimes> Showtimes { get; set; }
    }
}
