//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix_Apps
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromoCodes()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int PromoID { get; set; }
        public string PromoCode { get; set; }
        public decimal DiscountPercentage { get; set; }
        public decimal MaxDiscount { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
