//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix_Apps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showtimes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Showtimes()
        {
            this.SeatReservations = new HashSet<SeatReservations>();
            this.ShowtimeStatusChanges = new HashSet<ShowtimeStatusChanges>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int ShowtimeID { get; set; }
        public string ShowtimeCode { get; set; }
        public int MovieID { get; set; }
        public int StudioID { get; set; }
        public System.DateTime ShowDate { get; set; }
        public System.TimeSpan ShowTime { get; set; }
        public decimal BasePrice { get; set; }
        public Nullable<decimal> PremiumSeatPrice { get; set; }
        public Nullable<decimal> CoupleSeatPrice { get; set; }
    
        public virtual Movies Movies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatReservations> SeatReservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowtimeStatusChanges> ShowtimeStatusChanges { get; set; }
        public virtual Studios Studios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
