//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix_Apps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studios()
        {
            this.Seats = new HashSet<Seats>();
            this.Showtimes = new HashSet<Showtimes>();
            this.ShowtimeStatusChanges = new HashSet<ShowtimeStatusChanges>();
        }
    
        public int StudioID { get; set; }
        public int CinemaID { get; set; }
        public string StudioNumber { get; set; }
        public string StudioType { get; set; }
        public int TotalSeats { get; set; }
        public int TotalRows { get; set; }
        public int SeatsPerRow { get; set; }
    
        public virtual Cinemas Cinemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seats> Seats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Showtimes> Showtimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowtimeStatusChanges> ShowtimeStatusChanges { get; set; }
    }
}
