//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix_Apps
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetails
    {
        public int DetailID { get; set; }
        public int TransactionID { get; set; }
        public string PassengerName { get; set; }
        public string PassengerTitle { get; set; }
        public int SeatID { get; set; }
        public decimal TicketPrice { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
