//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaFlix_Apps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transactions()
        {
            this.SeatReservations = new HashSet<SeatReservations>();
            this.TransactionDetails = new HashSet<TransactionDetails>();
        }
    
        public int TransactionID { get; set; }
        public string TransactionCode { get; set; }
        public int CashierID { get; set; }
        public int ShowtimeID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public int TotalTickets { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<int> PromoID { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public decimal TotalPayment { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public Nullable<int> RefundBy { get; set; }
        public string RefundReason { get; set; }
    
        public virtual PromoCodes PromoCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatReservations> SeatReservations { get; set; }
        public virtual Showtimes Showtimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetails> TransactionDetails { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
